// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoymnAxYSAkRk6c0eWzLLVkIipHFcPsBo',
    appId: '1:329053429244:web:1fb48302e0fc12de0e2679',
    messagingSenderId: '329053429244',
    projectId: 'studaypoint-7f2fd',
    authDomain: 'studaypoint-7f2fd.firebaseapp.com',
    storageBucket: 'studaypoint-7f2fd.appspot.com',
    measurementId: 'G-HN1CNLGL8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlNHsPYoQYpg71FrMD_CaEWLAwEQ2mUQ',
    appId: '1:329053429244:android:62015eaecf9f12140e2679',
    messagingSenderId: '329053429244',
    projectId: 'studaypoint-7f2fd',
    storageBucket: 'studaypoint-7f2fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAmGsqF7mS3xpZVyhWy0irJcOblZurCiY',
    appId: '1:329053429244:ios:ca598bfe304095210e2679',
    messagingSenderId: '329053429244',
    projectId: 'studaypoint-7f2fd',
    storageBucket: 'studaypoint-7f2fd.appspot.com',
    iosBundleId: 'com.example.studaypoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAmGsqF7mS3xpZVyhWy0irJcOblZurCiY',
    appId: '1:329053429244:ios:f53c927627bd55e50e2679',
    messagingSenderId: '329053429244',
    projectId: 'studaypoint-7f2fd',
    storageBucket: 'studaypoint-7f2fd.appspot.com',
    iosBundleId: 'com.example.studaypoint.RunnerTests',
  );
}
